version: "3.1"

services:
  idp:
    container_name: "idp"
    build: ./idp
    ports:
      - '80:80'
      - '443:4443'
    volumes:
      - './config/idp/:/external-mount/'
    environment:
      JETTY_BROWSER_SSL_KEYSTORE_PASSWORD: ""
      JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD: backchannel
    restart: always
