version: "3.1"

services:
  idp:
    container_name: "idp"
    build: ./idp
    volumes:
      - './config/idp/:/external-mount/'
    environment:
      JETTY_BROWSER_SSL_KEYSTORE_PASSWORD: ""
      JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD: back
    restart: always
    depends_on:
      - "ldap"
      - "phpldapadmin"
      - "haproxy"
      - "httpd-metadata"

  ldap:
    container_name: "ldap"
    build: ./ldap
    ports:
      - '389:389'
    volumes:
      - './config/ldap:/var/lib/ldap'
    environment:
      LDAP_DOMAIN: "shib"
      LDAP_ORGANISATION: "Shibboleth United Ltd."
      LDAP_ROOTPASS: "toor"
    restart: always

  phpldapadmin:
    container_name: "phpldapadmin"
    build: ./phpldapadmin
    ports:
      - '88:80'
    environment:
      LDAP_SERVER_HOST: "ldap"
      LDAP_SERVER_PORT: "389"
      UNIQUE_ATTRS: "mail,uid,uidNumbers"
    restart: always
    depends_on:
      - "ldap"
  haproxy:
    restart: always
    #privileged: true
    container_name: 'haproxy'
    image: haproxy
    #environment:
    #network_mode: "host"
    ports:
     - '80:80'
     - '443:443'
     - '8443:8443'
    volumes:
      - './haproxy/:/usr/local/etc/haproxy/'
      
  httpd-metadata:
   image: php:7.0-apache
   container_name: 'httpd-metadata'
   volumes:
      - './httpd-metadata/html/:/var/www/html/'
   restart: always

